require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/schema.rb
    - db/seeds.rb
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
