language: ruby
# install: true
sudo: required

addons:
  chrome: stable
  apt:
    update: true
    packages:

rvm:
  - 2.6.3

services:
  - docker

cache:
  yarn: true
  directories:
    - vendor/bundle

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - gem install bundler -v 1.17.3

install:
  - docker-compose build
  - bundle update --retry=5 --jobs=20

script:
  - bundle exec rspec

after_script:
  - docker-compose down
