version: '3'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'
    ports:
      - "5432:5432"

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"

  api:
    container_name: api
    depends_on:
      - 'postgres'
      - 'redis'
    stdin_open: true
    tty: true
    build: .
    ports:
      - '8080:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  sidekiq:
    container_name: sidekiq
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  sidekiq-web:
    container_name: sidekiq-web
    command: bundle exec rackup -o 0.0.0.0 -p 3000 sidekiq-web.ru
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=${ACTIVE_JOB_URL}
    env_file:
      - '.env'
    depends_on:
      - redis

volumes:
  redis:
  postgres:
