name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.7
 
    - name: Pronto Ruby
      uses: AdWerx/pronto-ruby@v1.1.0

    - name: Rubocop checks
      uses: gimenete/rubocop-action@1.0

