version: 2.1

jobs:
  build:
    docker:
      - image: circleci/<< parameters.ruby_version >>
      - image: circleci/postgres:9.6.2-alpine
    parameters:
      ruby_version:
        type: string
      gemfile:
        type: string
    environment:
      BUNDLE_GEMFILE: << parameters.gemfile >>
    steps:
      - checkout
      # Restore Cached Dependencies
      # - restore_cache:
      #     keys:
      #       - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "<< parameters.gemfile >>.lock" }}
      #       - gem-cache-v1-{{ arch }}-{{ .Branch }}
      #       - gem-cache-v1

      - run: bundle install --path vendor/bundle

      # - save_cache:
      #     key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "<< parameters.gemfile >>.lock" }}
      #     paths:
      #       - vendor/bundle

      - run:
          name: Install postgres client
          command: sudo apt install -y postgresql-client

      - run:
          name: Configure config database.yml
          command: bundle exec rake db:copy_credentials

      - run:
          name: wait for postgresql
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:test:prepare
      - run:
          name: Run tests
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/test-results/rspec/rspec.xml

      - store_test_results:
          path: ~/test-results/rspec/

workflows:
  tests:
    jobs:
      - build:
          matrix:
            parameters:
              ruby_version: ["ruby:3.0.3-buster"]
              gemfile: ["Gemfile", "gemfiles/Gemfile.rails_6_1"]
