version: 2

jobs:
  build:
    working_directory: ~/budget-app-api
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          BUNDLER_VERSION: 2.1.4
          PGHOST: localhost
          PGUSER: budget-app-api
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123qweasd
          POSTGRES_DB: budget_app_api
    steps:
      - checkout
      - run:
        name: Force Bundler Version
        command: |
          sudo gem update --system
          echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
          source $BASH_ENV
          gem install bundler

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: budget_app_api-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: budget_app_api-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
    
      # Setup the environment
      # - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rspec
