version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    working_directory: ~/budget-app-api
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    steps:
      - checkout
      - ruby/install-deps
    
  test:
    parallelism: 3
    docker:
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: budget_app_api
          POSTGRES_PASSWORD: "123qweasd"
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: budget-app-api
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test  
    
workflows:
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
