version: 2

jobs:
  build:
    working_directory: ~/budget-app-api
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          BUNDLER_VERSION: 2.1.4
          PGHOST: localhost
          PGUSER: budget-app-api
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123qweasd
          POSTGRES_DB: budget_app_api

    steps:
      - checkout
      - attach_workspace:
          at: ~/budget-app-api

      - run:
          name: Install latest Bundler
          command: gem install bundler

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: budget_app_api-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: budget_app_api-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
    
      # Setup the environment
      # - run: cp .sample.env .env

  audits:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          BUNDLER_VERSION: 2.1.4
          PGHOST: localhost
          PGUSER: budget-app-api
          RAILS_ENV: test
    steps:
      - checkout
      - attach_workspace:
          at: ~/budget-app-api

      - run:
          name: bundle-audit
          command: bundle exec bundle-audit check --update

      - run:
          name: brakeman
          command: bundle exec brakeman --color -o brakeman_results.html -f plain

  tests:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          BUNDLER_VERSION: 2.1.4
          PGHOST: localhost
          PGUSER: budget-app-api
          RAILS_ENV: test
    parallelism: 1
    steps:
      - checkout
      - attach_workspace:
          at: ~/budget-app-api
      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      # - run: bundle exec rspec
      
      - run:
          name: Run unit tests
          command: |
            rspec --format RspecJunitFormatter \
                          --out test_results/rspec.xml \
                          --format progress
      - store_test_results:
          path: test_results

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - audits:
          requires:
            - build
      - tests:
          requires:
            - build
