# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/ruby:2.5.7
      environment:
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        RAILS_ENV: test
        ES_JAVA_OPTS: -Xms2g -Xmx2g
        _JAVA_OPTIONS: -Xms1024m -Xmx2048m
    - image: circleci/postgres:9.6.8-alpine-ram
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: project
        POSTGRES_PASSWORD: ""

jobs:
  build_rails_dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle-
      - run:
          name: Bundle install
          command: bundle check || bundle install
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ~/project
          paths:
            - vendor/bundle

  run_audits:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: bundle exec bundle-audit check --update
      - run: bundle exec brakeman --color -o brakeman_results.html -f plain

  run_unit_tests:
    <<: *defaults
    parallelism: 2
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Create DB
          command: bin/rails db:create db:schema:load --trace

      - run:
          name: Run unit tests              # NOTICE THE EXCLUDED features DIRECTORY BELOW
          command: |
            TEST_DIRS="controllers,jobs,lib,mailers,models,policies,queries,resources,tasks,
                       uploaders,validations,validators,workers"
            TEST_COMMAND="$(circleci tests glob "spec/{$TEST_DIRS}/**/*_spec.rb" |
                            circleci tests split --split-by=timings)"
            bundle exec rspec --exclude-pattern "spec/features/**/*_spec.rb" \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $TEST_COMMAND
      - store_test_results:
          path: test_results


workflows:
  version: 2
  build_test:
    jobs:
      - build_rails_dependencies
      - run_audits:
          requires:
            - build_rails_dependencies
      - run_unit_tests:
          requires:
            - build_rails_dependencies
