version: 2.1

jobs:
  build:
    docker:
      - image: circleci/<< parameters.ruby_version >>
        environment:
          GEMFILE_NAME: <<parameters.gemfile>>
#         DATABASE_URL: postgresql://root@localhost:5432/budget-app-api
          POSTGRES_USER: budget_app_api
          POSTGRES_PASSWORD: 123qweasd
          POSTGRES_DB: budget_app_api
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: budget_app_api
          POSTGRES_PASSWORD: 123qweasd
          POSTGRES_DB: budget_app_api

    parameters:
      ruby_version:
        type: string
      gemfile:
        type: string
    environment:
      BUNDLE_GEMFILE: << parameters.gemfile >>
    steps:
      - checkout
      # Restore Cached Dependencies
      # - restore_cache:
      #     keys:
      #       - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "<< parameters.gemfile >>.lock" }}
      #       - gem-cache-v1-{{ arch }}-{{ .Branch }}
      #       - gem-cache-v1

      - run: bundle install --path vendor/bundle

      # - save_cache:
      #     key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "<< parameters.gemfile >>.lock" }}
      #     paths:
      #       - vendor/bundle

      - run:
          name: wait for postgresql
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - resolve-dependencies
      - setup-postgres
      - run-tests-rspec

workflows:
  tests:
    jobs:
      - build:
          matrix:
            parameters:
              ruby_version: ["ruby:3.0-buster", "ruby:3.0.1-buster"]
              gemfile: ["Gemfile", "gemfiles/Gemfile.rails_6_1"]
