name: Ruby

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: budget_app_api
          POSTGRES_PASSWORD: 123qweasd
          POSTGRES_DB: budget_app_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    
    - name: install PostgreSQL client
      run: sudo apt-get install libpq-dev gsub
   
    - name: Build and test with Rake
      run: |
        sudo apt-get install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
